name: Sync AQHI Data

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Pollutant Data
        run: curl -sL "https://www.aqhi.gov.hk/epd/ddata/html/out/24pc_ChT.xml" -o data.xml

      - name: Download AQHI Index Data
        run: curl -sL "https://www.aqhi.gov.hk/epd/ddata/html/out/aqhi_ind_rss_ChT.xml" -o aqhi_index.xml

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.xml aqhi_index.xml
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update AQHI and 24hr Pollutant data" && git push)
